### PR TITLE
Flags

### PR DESCRIPTION
**Pull request by LYCChiang**
Added a way to choose a flag and add it to a node and delete it.

### CODE REVIEW

**Comment by JethroWarnett** [comment]
Bugs: 
- Flag is added only if I first double click the node
- Import with flags does not work
- When changing flag, the undo/redo takes more clicks then needed.
Other fixes requested:
- Font size must be increased

The flags work and are a nice work around. The number of tests is also very nice. Great Job.

**Comment by JethroWarnett** [comment]
Bugs: 
- When adding a flag, a picture of a flag is shown rather than the actual flag. Only when double clicking the node, is the actual flag shown.

All other bugs from previous comments are fixed. Nice work.

**Review by GattoPianista — APPROVED** [review]

**Review by mdeliso97 — APPROVED** [review]
- I would change the button name "Change Flag" into "Apply Flag" which is more clear what it makes, figured out after a few minutes how it works.
- The right toolbar looks weird to me, doesn't show it completely (cutted away). All options are overboarding the screen (you have to scroll right to see them entirely)
- The character used for al button label and the rest changed to me, is it normal?
Rest looks pretty good

**Review by JethroWarnett — APPROVED** [review]
Looks fine to me

**Pull request merged**
