### PR TITLE
Added grouping funktionality

### PR DESCRIPTION
**Pull request by mdeliso97**
Please check for bugs or problems that should be fixed so that me and Blendi can solve them until tuesday. Lawrence and Korab please look for the following problem solution:
- Actually when we try to change a group color and after change it again, those informations aren't stored, so they go lost withing a undo/redo or multiple of them.

### CODE REVIEW

**Comment by JethroWarnett** [comment]
Bugs:
- The node relabel pop up, doesn't disappear, when I click the canvas (it does when I drag it)
- Once a node is assigned to a group, I cannot reassign it
- I cannot assign nodes to groups I have created
- I can add numerous different groups with the same name (I can add 'new group' 3 times)

Other problems:
- It took me a long while until I understood how to change the groups of the nodes. There is no feedback that tells me what to do or what is happening.
- The label on top which shows the current selected group is hard to see
- The label on top causes a scrollbar to appear on the window. We want to avoid this.
- The default groups should be intuitive (ethical, unethical, sustainable etc. instead of group1, group2, group3).
- You have options 'none' and 'select group'. Remove 'select group'.

Deprecated:
- Remove node colouring

One refactor and this is very good.

**Review by JethroWarnett — CHANGES_REQUESTED** [review]
See comment

**Review by LYCChiang — APPROVED** [review]

**Comment by mdeliso97** [comment]
- Added fixes for different bugs that Jethro said.
- Added comments and ToDo comments
- Added group service
- Added snackbar service + functionality
- Added html code + .css for our implementation
- We have bug caused by update poUp Label from Jethro when trying to change color manually.
- -> Solution: delete manual color change

**Review by Korab-Bejta — APPROVED** [review]

**Comment by GattoPianista** [comment]
We created a new pull request with and updated branch

**Pull request closed without merging**
