### PR TITLE
Logo node

### PR DESCRIPTION
**Pull request by LYCChiang**
When you load the app, you can see a node with a image. Above is a button "import Logo" where you can select a different image for the node. The image selected becomes the new image of the Logo node.

### CODE REVIEW

**Review by JethroWarnett — CHANGES_REQUESTED** [review]
Bugs:
- I can delete the logo node
- The deleted logo node is not importet, when I press import logo node

A very nice implementation.

**Review by JethroWarnett — APPROVED** [review]
Issues:
- The snackbar should have the option 'no thanks', in case the user does not want a logo

Otherwise works great. The snackbar also looks cool.

**Comment by LYCChiang** [comment]
> Issues:
> 
>     * The snackbar should have the option 'no thanks', in case the user does not want a logo
> 
> 
> Otherwise works great. The snackbar also looks cool.

The snack bar fades away after 7 seconds. Do you think we need another button?

**Review by GattoPianista — APPROVED** [review]

**Review by mdeliso97 — APPROVED** [review]
The feature looks good. The imported picture looks really small but I don't think this is a big deal, it can always be impruved in the future.
Another things that might be improved in the future is the import quality of the picture, I tried to import a full HD picture and in the network it lost the high quality of the picture.

**Pull request merged**
