### PR TITLE
Refactor dynamic node relabelling

### PR DESCRIPTION
**Pull request by JethroWarnett**
Dynamic node relabelling is finished. Because of time constraints and complexity, node relabelling will not dynamically handle the user input (max character length, change size dynamically, etc.).

### CODE REVIEW

**Comment by Korab-Bejta** [comment]
I had the add node on while doubleclicking on a node and it first added a node then opened the dynamic node relabeling. After I finished relabeling the add node was still on, but i couldn't add more nodes, so I had to turn it off and on again.

**Comment by LYCChiang** [comment]
- If you have add edge mode on and you double click on a node to relabel it, you cannot add any more edges even though the edge mode is visually still on
- The logic that Korab and me implemented where flags don't show up in the dynamic relabeling box is broken. In other words, when you double click on a node to relabel it, it now shows the flag also, which is not good.
- Is it normal that when you are adding an edge, that the edge has a small blue dot at the tip?

But other than that, the renaming box looks much better and the bug Korab found is fixed nicely

**Review by GattoPianista — APPROVED** [review]

**Review by mdeliso97 — APPROVED** [review]
The implementation looks pretty good, I didn't find new bugs, the ones I found were the same as mentioned from Lawrence, but the thing that you can edit the flag also by doubleclick to change label, I found it user friendly as you can edit also the flag or even add a text near by the flag

**Comment by Korab-Bejta** [comment]
> The implementation looks pretty good, I didn't find new bugs, the ones I found were the same as mentioned from Lawrence, but the thing that you can edit the flag also by doubleclick to change label, I found it user friendly as you can edit also the flag or even add a text near by the flag

The thing is our implementation with the flags only works when the flag is above the text. otherwise we would have to do many different cases, where the flag is in the label.

**Pull request merged**
